typedef unsigned char   undefined;

typedef unsigned int    word;
typedef unsigned char    byte;
typedef struct OLD_IMAGE_DOS_HEADER OLD_IMAGE_DOS_HEADER, *POLD_IMAGE_DOS_HEADER;

struct OLD_IMAGE_DOS_HEADER {
    char e_magic[2]; // Magic number
    word e_cblp; // Bytes of last page
    word e_cp; // Pages in file
    word e_crlc; // Relocations
    word e_cparhdr; // Size of header in paragraphs
    word e_minalloc; // Minimum extra paragraphs needed
    word e_maxalloc; // Maximum extra paragraphs needed
    word e_ss; // Initial (relative) SS value
    word e_sp; // Initial SP value
    word e_csum; // Checksum
    word e_ip; // Initial IP value
    word e_cs; // Initial (relative) CS value
    word e_lfarlc; // File address of relocation table
    word e_ovno; // Overlay number
};




// WARNING: Instruction at (ram,0x00010268) overlaps instruction at (ram,0x00010267)
// 
// WARNING: Possible PIC construction at 0x00010168: Changing call to branch
// WARNING: Removing unreachable block (ram,0x0001016b)
// WARNING: Stack frame is not setup normally: Input value of stackpointer is not used
// WARNING: This function may have set the stack pointer
// WARNING: Removing unreachable block (ram,0x0001007a)
// WARNING: Removing unreachable block (ram,0x0001009c)

int entry(void)

{
  byte *pbVar1;
  char *pcVar2;
  uint *puVar3;
  undefined2 *puVar4;
  code **ppcVar5;
  undefined uVar6;
  code *pcVar7;
  code *pcVar8;
  char cVar9;
  byte bVar10;
  byte bVar11;
  char cVar12;
  byte bVar13;
  char cVar16;
  uint uVar14;
  uint uVar15;
  uint in_CX;
  int iVar17;
  int iVar18;
  char cVar19;
  byte extraout_DL;
  int iVar20;
  int in_BX;
  undefined *puVar21;
  undefined *puVar22;
  undefined2 *puVar23;
  undefined *puVar24;
  undefined *puVar25;
  undefined *puVar26;
  undefined2 *puVar27;
  char *unaff_BP;
  undefined2 *unaff_SI;
  uint *puVar28;
  undefined2 *puVar29;
  undefined2 *unaff_DI;
  code **ppcVar30;
  undefined2 unaff_ES;
  undefined2 uVar31;
  bool bVar32;
  undefined4 uVar33;
  
                    // WARNING: Read-only address (ram,0x000100b6) is written
  uRam000100b6 = 0x1000;
  puVar21 = (undefined *)0xb8;
  pcVar8 = (code *)swi(0x21);
  (*pcVar8)();
  pcVar8 = (code *)swi(0x21);
  uVar33 = (*pcVar8)();
  iVar20 = (int)((ulong)uVar33 >> 0x10);
  iVar17 = (int)uVar33;
  *(undefined **)(puVar21 + -2) = puVar21;
  puVar22 = puVar21 + -4;
  *(undefined2 *)(puVar21 + -4) = 0x7369;
  pbVar1 = (byte *)((int)unaff_SI + in_BX + 0x72);
  *pbVar1 = *pbVar1 & (byte)((ulong)uVar33 >> 0x18);
  out(*unaff_SI,iVar20);
  bVar13 = (byte)((ulong)uVar33 >> 8);
  cVar12 = (char)in_CX;
  bVar11 = (byte)(in_CX >> 8);
  ppcVar30 = (code **)(unaff_DI + 1);
  uVar31 = in(iVar20);
  *unaff_DI = uVar31;
  pbVar1 = (byte *)(unaff_BP + (int)ppcVar30 + 0x61);
  *pbVar1 = *pbVar1 & bVar13;
  out(*(undefined *)(unaff_SI + 1),iVar20);
  out(*(undefined *)((int)unaff_SI + 3),iVar20);
  puVar28 = unaff_SI + 3;
  out(unaff_SI[2],iVar20);
  if (*pbVar1 != 0) {
    puVar3 = puVar28;
    puVar28 = (uint *)((int)unaff_SI + 7);
    out(*(char *)puVar3,iVar20);
    pbVar1 = (byte *)((int)ppcVar30 + in_BX + 0x6e);
    *pbVar1 = *pbVar1 & bVar11;
    *(byte *)(unaff_SI + 0x2b) = *(byte *)(unaff_SI + 0x2b) & (byte)uVar33;
    *(int *)(puVar21 + -6) = in_BX;
    *(byte *)((int)unaff_DI + 0x71) = *(byte *)((int)unaff_DI + 0x71) & bVar11;
    iVar17 = (uint)(bVar13 | 10) << 8;
    *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28);
    *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28);
    *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28);
    puVar22 = puVar21 + -8;
    *(int *)(puVar21 + -8) = iVar17;
    unaff_BP = unaff_BP + 1;
  }
  cVar9 = (char)iVar17;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  iRam00008100 = iRam00008100 + iVar17;
  cVar16 = (char)((uint)iVar17 >> 8);
  (unaff_BP + (int)ppcVar30)[0x32] = cVar16;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  uVar14 = CONCAT11(cVar16,cVar9 + cVar16);
  cRam00000b01 = cRam00000b01 + cVar12;
  puVar3 = puVar28;
  uVar15 = *puVar3;
  *puVar3 = *puVar3 + uVar14;
  cVar9 = cVar9 + cVar16 + CARRY2(uVar15,uVar14);
  iVar20 = iVar20 + -1;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  cVar19 = (char)((uint)iVar20 >> 8);
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar19;
  uVar31 = *(undefined2 *)(puVar22 + -1);
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  bVar10 = cVar9 + cVar19;
  iVar17 = CONCAT11(cVar16,bVar10);
  *(int *)(in_BX + (int)puVar28) = *(int *)(in_BX + (int)puVar28) - iVar17;
  pbVar1 = (byte *)(in_BX + (int)puVar28);
  bVar13 = *pbVar1;
  *pbVar1 = *pbVar1 + bVar10;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + bVar10 + CARRY1(bVar13,bVar10)
  ;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + bVar10;
  *(int *)(puVar22 + -1) = iVar17;
  *(uint *)(puVar22 + -3) = in_CX;
  *(int *)(puVar22 + -5) = iVar20;
  *(int *)(puVar22 + -7) = in_BX;
  *(undefined **)(puVar22 + -9) = puVar22 + 1;
  *(char **)(puVar22 + -0xb) = unaff_BP;
  *(uint **)(puVar22 + -0xd) = puVar28;
  *(code ***)(puVar22 + -0xf) = ppcVar30;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + bVar10;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + bVar10;
  pbVar1 = (byte *)(in_BX + (int)puVar28);
  bVar13 = *pbVar1;
  bVar10 = (byte)(iVar17 + 1);
  *pbVar1 = *pbVar1 + bVar10;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + bVar10 + CARRY1(bVar13,bVar10)
  ;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + bVar10;
  cVar16 = (char)((uint)(iVar17 + 1) >> 8);
  cVar9 = bVar10 + *(char *)(in_BX + (int)puVar28);
  *(char *)puVar28 = *(char *)puVar28 + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)puVar28 = *(char *)puVar28 + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar9;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  unaff_BP[(int)puVar28] = unaff_BP[(int)puVar28] + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  cVar19 = (char)iVar20;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar19;
  pbVar1 = (byte *)(in_BX + (int)puVar28);
  bVar13 = *pbVar1;
  *pbVar1 = *pbVar1 + 7;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a' + (0xf8 < bVar13);
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar19;
  pbVar1 = (byte *)(in_BX + (int)puVar28);
  bVar13 = *pbVar1;
  *pbVar1 = *pbVar1 + 7;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a' + (0xf8 < bVar13);
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar19;
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + '\a';
  *(char *)(in_BX + (int)puVar28) = *(char *)(in_BX + (int)puVar28) + cVar16;
  puVar29 = (undefined2 *)((int)puVar28 + 1);
  cVar9 = *(char *)puVar28;
  bRam00000000 = bRam00000000 + 1;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar9;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar9;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar9;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar9;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar9;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar9;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar9;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar9;
  bVar13 = bRam00000007;
  iVar17 = CONCAT11(cVar16,bRam00000007);
  puVar23 = (undefined2 *)(puVar22 + -0x11);
  *(int *)(puVar22 + -0x11) = iVar17;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  pcVar2 = (char *)(in_BX + (int)puVar29);
  *pcVar2 = *pcVar2 + cVar12;
  if (*pcVar2 == '\0') {
code_r0x000101a0:
    cVar12 = (char)in_CX;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    in_CX = in_CX + 1;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + (char)in_CX;
    bRam00006469 = bRam00006469 >> 1;
    if (bRam00006469 == 0) goto code_r0x00010217;
code_r0x000101b6:
    cVar12 = (char)in_CX;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(uint *)(in_BX + (int)puVar29) = *(uint *)(in_BX + (int)puVar29) | in_CX;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    unaff_BP[(int)puVar29] = unaff_BP[(int)puVar29] + (char)iVar17;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)puVar29 = *(char *)puVar29 + (char)(in_CX >> 8);
code_r0x000101c7:
    bVar13 = (byte)in_CX;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
    cVar12 = bVar13 * '\x02';
    if (!CARRY1(bVar13,bVar13)) {
      if (!CARRY1(bVar13,bVar13)) {
        *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
        *(char *)(puVar29 + 0x37f) = *(char *)(puVar29 + 0x37f) + (char)((uint)iVar17 >> 8);
        *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
        bVar13 = bRam00000000;
        uVar15 = (uint)bRam00000000;
        *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bRam00000000;
        uVar31 = *puVar23;
        puVar23 = puVar23 + 1;
        *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
        puVar4 = puVar29;
        puVar29 = (undefined2 *)((int)puVar29 + 1);
        out(*(char *)puVar4,iVar20);
        goto code_r0x000101ee;
      }
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    }
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  }
  else {
    if (*pcVar2 < '\0') {
      puVar23 = (undefined2 *)(puVar28[0x31] * 0x6174);
      goto code_r0x000101b6;
    }
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    in_CX = CONCAT11(bVar11,cVar12 + cVar16) - 1;
    bVar10 = (byte)in_CX;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar19;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    unaff_BP[(int)puVar29] = unaff_BP[(int)puVar29] + bVar13;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar10;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + (char)(in_CX >> 8);
    pbVar1 = (byte *)(in_BX + (int)puVar29);
    bVar13 = *pbVar1;
    *pbVar1 = *pbVar1 + bVar10;
    bVar11 = *pbVar1;
    *(uint *)(puVar22 + -0x13) = in_CX;
    *(int *)(puVar22 + -0x15) = iVar17;
    *(int *)(puVar22 + -0x17) = iVar20;
    *(int *)(puVar22 + -0x19) = in_BX;
    *(undefined **)(puVar22 + -0x1b) = puVar22 + -0x11;
    *(char **)(puVar22 + -0x1d) = unaff_BP;
    *(undefined2 **)(puVar22 + -0x1f) = puVar29;
    puVar23 = (undefined2 *)(puVar22 + -0x21);
    *(code ***)(puVar22 + -0x21) = ppcVar30;
    if (CARRY1(bVar13,bVar10)) goto code_r0x000101c7;
    ppcVar30 = *(code ***)(puVar22 + -0x21);
    puVar29 = *(undefined2 **)(puVar22 + -0x1f);
    unaff_BP = *(char **)(puVar22 + -0x1d);
    in_BX = *(int *)(puVar22 + -0x19);
    iVar20 = *(int *)(puVar22 + -0x17);
    iVar17 = *(int *)(puVar22 + -0x15);
    in_CX = *(uint *)(puVar22 + -0x13);
    puVar23 = (undefined2 *)(puVar22 + -0x11);
    if (bVar11 == 0) goto code_r0x000101c7;
    cVar12 = (char)in_CX;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(undefined2 *)(puVar22 + -0x13) = 0x16b;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)puVar29 = *(char *)puVar29 + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *unaff_BP = *unaff_BP + (char)iVar17;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    pcVar2 = (char *)((int)puVar29 + in_BX + 0x2e);
    *pcVar2 = *pcVar2 + cVar12;
    ppcVar30 = *(code ***)(puVar22 + -0x13);
    puVar29 = *(undefined2 **)(puVar22 + -0x11);
    unaff_BP = *(char **)(puVar22 + -0xf);
    in_BX = *(int *)(puVar22 + -0xb);
    iVar20 = *(int *)(puVar22 + -9);
    iVar17 = *(int *)(puVar22 + -7);
    uVar15 = *(uint *)(puVar22 + -5);
    puVar23 = (undefined2 *)(puVar22 + -3);
    if (*pcVar2 != '\0') {
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + (char)uVar15;
      bVar10 = (byte)(uVar15 >> 8);
      bVar11 = (char)uVar15 + CARRY1(bVar10,bVar10);
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar11;
      pbVar1 = (byte *)(in_BX + (int)puVar29);
      bVar13 = *pbVar1;
      *pbVar1 = *pbVar1 + bVar11;
      cVar12 = bVar11 + *(char *)(in_BX + (int)puVar29) + CARRY1(bVar13,bVar11);
      in_CX = CONCAT11(bVar10 * '\x02',cVar12);
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      puVar23 = (undefined2 *)(puVar22 + -5);
      *(int *)(puVar22 + -5) = iVar20;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      goto code_r0x000101a0;
    }
code_r0x000101ee:
    cVar12 = (char)uVar15;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
    pbVar1 = (byte *)(in_BX + (int)puVar29);
    bVar32 = CARRY1(*pbVar1,cVar12 + 1U);
    *pbVar1 = *pbVar1 + cVar12 + 1U;
    cVar12 = (char)(uVar15 + 2);
    if (!bVar32) {
      ppcVar5 = ppcVar30;
      ppcVar30 = (code **)((int)ppcVar30 + 1);
      uVar6 = in(iVar20);
      *(undefined *)ppcVar5 = uVar6;
      puVar4 = puVar29;
      puVar29 = puVar29 + 1;
      out(*puVar4,iVar20);
      puVar3 = (uint *)(in_BX + (int)puVar29);
      *puVar3 = *puVar3 + (uint)bVar32 * ((uVar15 + 2 & 3) - (*puVar3 & 3));
      cVar9 = (char)((uint)iVar17 >> 8);
      *(char *)(in_BX + (int)puVar29) =
           *(char *)(in_BX + (int)puVar29) +
           (cVar12 + cVar9 | (byte)*(undefined2 *)(in_BX + (int)puVar29));
      bVar13 = bRam00000007;
      in_CX = (uint)bRam00000007;
      *(char *)puVar29 = *(char *)puVar29 + (char)iVar17;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + bVar13;
      unaff_BP[7] = unaff_BP[7] + cVar9;
code_r0x00010217:
      cVar12 = (char)in_CX;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      unaff_BP[(int)puVar29] = unaff_BP[(int)puVar29] + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
      unaff_BP[(int)ppcVar30] = unaff_BP[(int)ppcVar30] + (char)((uint)iVar20 >> 8);
      pbVar1 = (byte *)((int)ppcVar30 + in_BX + 0x3441);
      *pbVar1 = *pbVar1 >> 1 | *pbVar1 << 7;
      iVar18 = iVar17 + 2;
      (unaff_BP + (int)ppcVar30)[-0x3c3f] = (unaff_BP + (int)ppcVar30)[-0x3c3f] | (byte)iVar18;
      puVar25 = (undefined *)((int)puVar23 + -2);
      *(char **)((int)puVar23 + -2) = (char *)puVar29;
      iVar20 = *(int *)((int)ppcVar30 + in_BX + 0x34);
      if (iVar20 != 0) {
        *(int *)((int)puVar23 + -4) = iVar20;
        puVar24 = (undefined *)((int)puVar23 + -6);
        *(undefined2 *)((int)puVar23 + -6) = 0x3de;
        cVar12 = func_0x000118be();
        *(char *)(in_BX + iVar18) = *(char *)(in_BX + iVar18) + cVar12;
        puVar25 = puVar24 + 4;
      }
      bVar32 = *(int *)(unaff_BP + 0x38) == 0;
      if (!bVar32) {
        *(int *)(puVar25 + -2) = *(int *)(unaff_BP + 0x38);
        puVar26 = puVar25 + -4;
        *(undefined2 *)(puVar25 + -4) = 0x3ee;
        cVar12 = func_0x000118be();
        *(char *)(in_BX + iVar18) = *(char *)(in_BX + iVar18) + cVar12;
        puVar25 = puVar26 + 4;
        bVar32 = puVar26 == (undefined *)0xfffc;
      }
      if (!bVar32) {
        *(undefined2 *)(puVar25 + -2) = uRam0000c085;
        pcVar7 = *ppcVar30;
        puVar27 = (undefined2 *)(puVar25 + -4);
        puVar25 = puVar25 + -4;
        *puVar27 = 0x3fc;
        (*pcVar7)();
        unaff_BP[iVar17 + 0x42] = unaff_BP[iVar17 + 0x42] & extraout_DL;
      }
      iVar17 = *(int *)(unaff_BP + 8);
      if (iVar17 != 0) {
        *(int *)(puVar25 + -2) = iVar17;
        *(undefined2 *)(puVar25 + -4) = 0x40b;
        iVar17 = func_0x000118be();
        *(char *)(in_BX + iVar18) = *(char *)(in_BX + iVar18) + (char)iVar17;
      }
      return iVar17;
    }
  }
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(char *)(in_BX + (int)puVar29) = *(char *)(in_BX + (int)puVar29) + cVar12;
  *(undefined2 *)((int)ppcVar30 + in_BX + 0x34) = 0;
  *(undefined2 *)((int)ppcVar30 + in_BX + 0x38) = 0;
  *(undefined2 *)(in_BX + (int)ppcVar30) = 0;
  *(undefined2 *)((int)ppcVar30 + in_BX + 8) = 0;
  return iVar17;
}


